extends Control
@onready var option_popup = $OptionPopup
func _ready():
	$VBoxContainer/start.connect("pressed", Callable(self, "_on_start_pressed"))
	$VBoxContainer/exit.connect("pressed", Callable(self, "_on_exit_pressed"))
	$VBoxContainer/option.connect("pressed", Callable(self, "_on_Opcje_pressed"))



func _on_Opcje_pressed():
	option_popup.popup_centered()


func _on_start_pressed():
	get_tree().change_scene_to_file("res://scenes/galaxy.tscn")
	MusicManager.play_music()

func _on_exit_pressed():
	get_tree().quit()
